name: event

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - run: sudo apt-get install -y libsdl2-dev

    - uses: actions/checkout@v3

    - uses: haskell-actions/setup@v2
      with:
        ghc-version: 9.8.1

    - uses: actions/cache@v3
      with:
        key: event-build
        path: |
          ${{ steps.setup.outputs.cabal-store }}
          dist-newstyle
          ~/.ghcup

    - run: cabal update

    - run: cabal build event --only-dependencies

    - run: cabal build event --ghc-options=-Werror

    - run: cabal build event:test:tests --ghc-options=-Werror

    - run: cabal test event -- --randomize
