name: named

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - run: sudo apt-get install -y libsdl2-dev libpcre3-dev

    - uses: actions/checkout@v3

    - uses: haskell-actions/setup@v2
      id: setup
      with:
        ghc-version: 9.8.1

    - uses: actions/cache@v3
      with:
        key: named-build
        path: |
          ${{ steps.setup.outputs.cabal-store }}
          dist-newstyle
          ~/.ghcup

    - run: cabal update

    - run: cabal build named --only-dependencies

    - run: cabal build named --ghc-options=-Werror

    - run: cabal build named:test:tests --ghc-options=-Werror

    - run: cabal test named
