name: paparazzi

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - run: sudo apt-get install -y ffmpeg libsdl2-dev

    - uses: actions/checkout@v3

    - uses: haskell-actions/setup@v2
      id: setup
      with:
        ghc-version: 9.8.1

    - uses: actions/cache@v3
      with:
        key: paparazzi-build
        path: |
          ${{ steps.setup.outputs.cabal-store }}
          dist-newstyle
          ~/.ghcup

    - run: cabal update

    - run: cabal build paparazzi --only-dependencies

    - run: cabal build paparazzi --ghc-options=-Werror

    - run: cabal build paparazzi:test:tests --ghc-options=-Werror

    - uses: GabrielBB/xvfb-action@v1
      with:
        run: cabal test paparazzi -- --randomize
