name: postfix

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - run: sudo apt-get install -y libsdl2-dev

    - uses: actions/checkout@v3

    - uses: haskell-actions/setup@v2
      id: setup
      with:
        ghc-version: 9.8.1

    - uses: actions/cache@v3
      with:
        key: postfix-build
        path: |
          ${{ steps.setup.outputs.cabal-store }}
          dist-newstyle
          ~/.ghcup

    - run: cabal update

    - run: cabal build postfix --only-dependencies

    - run: cabal build postfix --ghc-options=-Werror

    - run: cabal build postfix:test:tests --ghc-options=-Werror

    - run: cabal test postfix
