name: test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: haskell/actions/setup@v2
      with:
        ghc-version: 9.2.4

    - uses: actions/cache@v3
      with:
        key: ${{ inputs.package }}-build
        path: |
          ${{ steps.setup.outputs.cabal-store }}
          dist-newstyle
          ~/.ghcup

    - cabal update

    - cabal build ${{ inputs.package }} --only-dependencies

    - cabal build ${{ inputs.package }} --ghc-options=-Werror

    - cabal test all
