name: variant

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - run: sudo apt-get install -y libsdl2-dev

    - uses: actions/checkout@v3

    - uses: haskell-actions/setup@v2
      id: setup
      with:
        ghc-version: 9.8.1

    - uses: actions/cache@v3
      with:
        key: variant-build
        path: |
          ${{ steps.setup.outputs.cabal-store }}
          dist-newstyle
          ~/.ghcup

    - run: cabal update

    - run: cabal build variant --only-dependencies

    - run: cabal build variant --ghc-options=-Werror

    - run: cabal build variant:test:tests --ghc-options=-Werror

    - run: cabal test variant -- --randomize
